tasks/urls.py
from django.urls import path

from tasks.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskStatusUpdateView
)

urlpatterns = [
    path(
        "",
        TaskListView.as_view(),
        name="TaskListView"
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create",
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "task-status/<int:pk>/",
        TaskStatusUpdateView.as_view(),
        name="change-task"
    ),
    path(
        "tags/",
        TagListView.as_view(),
        name="TagListView"
    ),
    path(
        "tags/create/",
        TagCreateView.as_view(),
        name="tag-create",
    ),
    path(
        "tags/<int:pk>/update/",
        TagUpdateView.as_view(),
        name="tag-update"
    ),
    path(
        "tags/<int:pk>/delete/",
        TagDeleteView.as_view(),
        name="tag-delete"
    ),
]

app_name = "tasks"

todo_list/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tasks.urls", namespace="tasks")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tags", blank=True)

    class Meta:
        ordering = ["is_done", "datetime"]

tasks/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic, View
from tasks.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    template_name = "tasks/index.html"
    context_object_name = "tasks_list"


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("tasks:TaskListView")
    template_name = "tasks/task_form.html"


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("tasks:TaskListView")
    template_name = "tasks/task_form.html"


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("tasks:TaskListView")
    template_name = "tasks/task_confirm_delete.html"


class TagListView(generic.ListView):
    model = Tag
    template_name = "tasks/tag_list.html"
    context_object_name = "tags_list"


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:TagListView")
    template_name = "tasks/tag_form.html"


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:TagListView")
    template_name = "tasks/tag_form.html"


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("tasks:TagListView")
    template_name = "tasks/tag_confirm_delete.html"


class TaskStatusUpdateView(View):
    @staticmethod
    def post(request, pk):
        task = Task.objects.get(id=pk)
        task.is_done = not task.is_done
        task.save()
        return redirect("tasks:TaskListView")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}
    <title>ToDo List</title>
  {% endblock %}
  <meta charset="utf=8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
  <div class = "row">
    <div class="col-sm-3">
      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}
    </div>
    <div class="col-sm-9">
      {% block content %}{% endblock %}
    </div>
  </div>
</div>
</body>
</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'tasks:TaskListView' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'tasks:TagListView' %}">Tags</a></li>
</ul>

templates/tasks/index.html
{% extends "base.html" %}

{% block content %}
  <h1>ToDo List</h1>
    <a class="btn btn-primary"  href="{% url 'tasks:task-create' %}">Add task</a>


  {% for task in tasks_list %}
        <h3>
          {{ task.content }}
          {% if task.is_done %}
            <a style="color:green">Done</a>
          {% else %}
            <a style="color:red;">Not done</a>
          {% endif %}
        </h3>

    <h5>Created: {{ task.datetime }} Deadline: {{ task.deadline }}</h5>
        <h7>Tags:
      {% for tag in task.tags.all %}
        {{ tag.name }}
    </h7>
      {% endfor %}
      <a class="btn btn-warning" href="{% url "tasks:task-update" pk=task.pk %} ">UPDATE</a>
      <a class="btn btn-danger" href="{% url "tasks:task-delete" pk=task.pk %} ">DELETE</a>
      <hr>
        {% if task.is_done %}
          <form action="{% url 'tasks:change-task' pk=task.id %}" method="POST">
            {% csrf_token %}
            <button class="btn btn-secondary" style="float: right; margin-top: -100px;">Undo</button>
          </form>
        {% else %}
          <form action="{% url 'tasks:change-task' pk=task.id %}" method="POST">
            {% csrf_token %}
            <button class="btn btn-success" style="float: right; margin-top: -100px;">Complete</button>
          </form>
        {% endif %}

  {% endfor %}
{% endblock %}

templates/tasks/tag_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete tag</h1>

  <p>Are you sure you want to delete: {{ tag }}?</p>

  <form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete" class="btn btn-danger" />
  </form>
{% endblock %}

templates/tasks/tag_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <br>

  <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/tasks/tag_list.html
{% extends "base.html" %}

{% block content %}

<h1>Tags
  <a class="btn btn-primary" href="{% url 'tasks:tag-create' %}">Add</a>
</h1>
  {% if tags_list %}
    <table class="table">
      <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Update</th>
          <th>Delete</th>
        </tr>
      {% for tag in tags_list %}
            <tr>
            <td>
              {{ tag.id }}
            </td>
              <td>
              {{ tag.name }}
            </td>
              <td>
              <a class="btn btn-warning" href="{% url "tasks:tag-update" pk=tag.id %} ">UPDATE</a>
              </td>
             <td>
              <a class="btn btn-danger" href="{% url "tasks:tag-delete" pk=tag.id %} ">DELETE</a>
              </td>
            </tr>
          {% endfor %}
    </table>
  {% else %}
    <p>There are no tags!</p>
  {% endif %}
{% endblock %}

templates/tasks/task_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Delete task</h1>

  <p>Are you sure you want to delete: {{ task }}?</p>

  <form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete" class="btn btn-danger" />
  </form>
{% endblock %}

templates/tasks/task_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <br>

  <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}